### ISSUE TITLE
trying to use it to retrain yamnet  with 2 classes model gets built but doesn't check properly

### ISSUE THREAD

**Issue by nimnim111** [KosminD/YAMNet_transfer#1]
Error:

=====
Wed Jan  5 19:14:41 2022 | Done
=====

=====
Wed Jan  5 19:14:41 2022 | Making TF-Lite SavedModel export ...
=====

2022-01-05 19:14:41.252616: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.

=====
Wed Jan  5 19:14:50 2022 | Done
=====

=====
Wed Jan  5 19:14:50 2022 | Checking TF-Lite SavedModel export in TF2 ...
=====

=====
Wed Jan  5 19:14:53 2022 | Done
=====

=====
Wed Jan  5 19:14:53 2022 | Making TF-Lite model ...
=====

2022-01-05 19:14:56.700458: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:363] Ignored output_format.
2022-01-05 19:14:56.700499: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:366] Ignored drop_control_dependency.
2022-01-05 19:14:56.700503: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:372] Ignored change_concat_input_ranges.
2022-01-05 19:14:56.701220: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: finalized_model/saved_model
2022-01-05 19:14:56.724514: I tensorflow/cc/saved_model/reader.cc:107] Reading meta graph with tags { serve }
2022-01-05 19:14:56.724557: I tensorflow/cc/saved_model/reader.cc:148] Reading SavedModel debug info (if present) from: finalized_model/saved_model
2022-01-05 19:14:56.809831: I tensorflow/cc/saved_model/loader.cc:210] Restoring SavedModel bundle.
2022-01-05 19:14:57.028822: I tensorflow/cc/saved_model/loader.cc:194] Running initialization op on SavedModel bundle at path: finalized_model/saved_model
2022-01-05 19:14:57.152454: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 451235 microseconds.
2022-01-05 19:14:57.395749: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded

=====
Wed Jan  5 19:14:57 2022 | Done
=====

=====
Wed Jan  5 19:14:57 2022 | Checking TF-Lite model ...
=====

Traceback (most recent call last):
  File "export.py", line 226, in <module>
    main(sys.argv[1:])
  File "export.py", line 221, in main
    make_tflite_export(weights_path, model_path, export_dir)
  File "export.py", line 183, in make_tflite_export
    check_model(run_model, 'yamnet_class_map.csv', params)
  File "export.py", line 78, in check_model
    clip_test(
  File "export.py", line 75, in clip_test
    top_n_class_names = yamnet_classes[top_n_indices]
IndexError: index 531 is out of bounds for axis 0 with size 2

**Comment by nimnim111** [comment]
btw same issue with original yamnet_class_map.csv instead of modified  with same modified training data

Traceback (most recent call last):
  File "export.py", line 226, in <module>
    main(sys.argv[1:])
  File "export.py", line 221, in main
    make_tflite_export(weights_path, model_path, export_dir)
  File "export.py", line 183, in make_tflite_export
    check_model(run_model, 'yamnet_class_map.csv', params)
  File "export.py", line 78, in check_model
    clip_test(
  File "export.py", line 75, in clip_test
    top_n_class_names = yamnet_classes[top_n_indices]
IndexError: index 719 is out of bounds for axis 0 with size 521
